import { api,LightningElement } from 'lwc';
import { NavigationMixin } from 'lightning/navigation';

export default class Dese_document_library extends NavigationMixin(LightningElement) {
    @api recordId = '';
    documentsPresent = true;
    showSpinner = false;
    isGsaOrRpRecord = false;
    editMode = false;
    tableData = [
        {
            "categoryName": "Residential Policy Verification",
            "innerFields": [
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1Bf10000055BWfEAM",
                    "documentName": "Statement of Purpose",
                    "documentNotApplicable": false,
                    "documentTypeName": "1. Statement of purpose as required by 102 CMR 3.04(1)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": false,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": false,
                    "isUnsubmitted": false,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Provider",
                    "status": "Reviewed",
                    "uploadedDate": "2018-09-13"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApagUAC",
                    "documentName": "Statement of Ownership",
                    "documentNotApplicable": false,
                    "documentTypeName": "2. Statement of the ownership of the program, including names and addresses of all owners, or  in the case of corporations, the officers as required by 102 CMR 3.04(2)(a)2",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Submitted"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000008fO9DUAU",
                    "documentName": "Operating Budget / Documentation of Funds",
                    "documentNotApplicable": false,
                    "documentTypeName": "3. Projected one year operating budget, and; documentation of sufficient funds for at least 3 months; For an operating agency, a current audited financial report, appropriate fiscal portions of contracts if any, and a statement of the current rate of payment as set by the  Commonwealth, if applicable or evidence of prequalification.",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Reviewed"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000008fO9EUAU",
                    "documentName": "Description of Intended Staffing / Statement of Ratio",
                    "documentNotApplicable": false,
                    "documentTypeName": "4. Description of the intended staffing of the facility or program on a 24 hour per day, seven  day per week basis including availability of on-call staff, statement of ratio for all shifts and four (4) weeks of staffing schedules, as required by 3.07(2)b",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Reviewed"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000008fO96UAE",
                    "documentName": "Organization Chart",
                    "documentNotApplicable": false,
                    "documentTypeName": "5. Organizational table, as required by 102 CMR 3.04(2)(C)",
                    "documentTypeNotApplicable": false,
                    "expirationDate": "2022-07-07",
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Reviewed",
                    "uploadedDate": "2021-07-07"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006AUppUAG",
                    "documentName": "Internal Investigation Policy",
                    "documentNotApplicable": false,
                    "documentTypeName": "6. Policy and procedure for internal investigations of child abuse and neglect as required by 102 CMR 3.04(3)(e)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-09"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006AezfUAC",
                    "documentName": "Compaint and Greivance Procedures",
                    "documentNotApplicable": false,
                    "documentTypeName": "7. Procedures regarding complaints and grievances, as required by 102 CMR 3.04(3) (i)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Submitted",
                    "uploadedDate": "2019-08-23"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006AfSFUA0",
                    "documentName": "Personnel Policies",
                    "documentNotApplicable": false,
                    "documentTypeName": "8. Personnel policies, as required by 102 CMR 3.04(6)(a)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-05-31"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006AfP4UAK",
                    "documentName": "Job Descriptions",
                    "documentNotApplicable": false,
                    "documentTypeName": "9. Job descriptions, as required by 102 CMR 3.04(6)(C)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-05-31"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApahUAC",
                    "documentName": "Salary Ranges",
                    "documentNotApplicable": false,
                    "documentTypeName": "10. Salary ranges, as required by 102 CMR 3.04(6)(d)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Unsubmitted"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApaWUAS",
                    "documentName": "Plan for Using Volunteers",
                    "documentNotApplicable": false,
                    "documentTypeName": "11. Plan for using volunteers, as required by 102 CMR 3.04(6)(g)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApaXUAS",
                    "documentName": "Plan for Staff Orientation and Training and Restraint Curricula",
                    "documentNotApplicable": false,
                    "documentTypeName": "12. Plan for staff orientation and training as required by 102 CMR 3.04(7) and restraint training  curricula, as required by 102 CMR 3.04(7)(a)(1)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApaYUAS",
                    "documentName": "Plan for Referral Service",
                    "documentNotApplicable": false,
                    "documentTypeName": "13. Plan for referral services, as required by 102 CMR 3.05(1)(i)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006AfERUA0",
                    "documentName": "Placement Agreement",
                    "documentNotApplicable": false,
                    "documentTypeName": "14. Agreement with the placement agency, purchaser of services and parent or guardian, as  required by 102 CMR 3.05(2)(d); Please submit a copy of the placement agreement",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Submitted"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1Bf1000004x8MkEAI",
                    "documentName": "Service Planning/ Advanced Degree Person",
                    "documentNotApplicable": false,
                    "documentTypeName": "15. Evidence of ability to comply with 102 CMR 3.05(4)(a), including a copy of the advanced  degree person's resume and a sample service plan template",
                    "documentTypeNotApplicable": false,
                    "expirationDate": "2019-11-20",
                    "helpText": "",
                    "isLegacyDocumentType": false,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": false,
                    "isUnsubmitted": false,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Provider",
                    "status": "Reviewed",
                    "uploadedDate": "2018-11-20"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApaZUAS",
                    "documentName": "Plan for Family Work",
                    "documentNotApplicable": false,
                    "documentTypeName": "16. Plan for family work, as required by 102 CMR 3.06(2)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApaaUAC",
                    "documentName": "Plan for Social, Psychological and Psychiatric Services",
                    "documentNotApplicable": false,
                    "documentTypeName": "17. Plan for social, psychological and psychiatric services, as required by 102 CMR 3.06(3)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApabUAC",
                    "documentName": "Plan for Emergency Medical and Evidence of Access to Emergency Mental Health",
                    "documentNotApplicable": false,
                    "documentTypeName": "18. Plan for meeting the emergency medical needs of children and evidence of access to  emergency mental health services, as required by 102 CMR 3.06(4)(a) and 3.06(3)(a)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApaVUAS",
                    "documentName": "Plan for Health Services",
                    "documentNotApplicable": false,
                    "documentTypeName": "19.  Plan for health services, as required by 102 CMR 3.06(4)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1Bf1000004x8MmEAI",
                    "documentName": "Evidence of Access to Schools",
                    "documentNotApplicable": false,
                    "documentTypeName": "20. Evidence of access to schools for the provision of any necessary educational services",
                    "documentTypeNotApplicable": false,
                    "expirationDate": "2019-12-06",
                    "helpText": "",
                    "isLegacyDocumentType": false,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": false,
                    "isUnsubmitted": false,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Provider",
                    "status": "Reviewed",
                    "uploadedDate": "2018-12-06"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApaUUAS",
                    "documentName": "Plan for Medication Administration",
                    "documentNotApplicable": false,
                    "documentTypeName": "21. Plan for administration of medication, as required by 102 CMR 3.06(4)(k)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Submitted",
                    "uploadedDate": "2019-08-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000008fO97UAE",
                    "documentName": "Educational Services",
                    "documentNotApplicable": false,
                    "documentTypeName": "22. Plan for educational services, as required by 102 CMR 3.06(5)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Reviewed"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApacUAC",
                    "documentName": "Vocational Services Policy",
                    "documentNotApplicable": false,
                    "documentTypeName": "23. Plan for vocational services, as required by 102 CMR 3.06(6)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApadUAC",
                    "documentName": "Recreation Policy",
                    "documentNotApplicable": false,
                    "documentTypeName": "24. Plan for recreational services, as required by 102 CMR 3.06(7)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000008fO98UAE",
                    "documentName": "Follow Up Services Policy",
                    "documentNotApplicable": false,
                    "documentTypeName": "25. Plan for follow-up services, as required by 102 CMR 3.06(12)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApaiUAC",
                    "documentName": "Nutritional Services Policy",
                    "documentNotApplicable": false,
                    "documentTypeName": "26. Plan for nutritional services, as required by 102 CMR 3.07(6), submit four weeks of menus",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006AUpkUAG",
                    "documentName": "Behavior Management Policy, Including Physical Restraint",
                    "documentNotApplicable": false,
                    "documentTypeName": "27. Behavior management policy, including physical restraint curriculum, as required by  102 CMR 3.07(7).",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000008fO99UAE",
                    "documentName": "Allowance Policy",
                    "documentNotApplicable": false,
                    "documentTypeName": "28. Allowance policy, as required by 102 CMR 3.07(8)(b)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApaeUAC",
                    "documentName": "Visiting Mail Telephone Policies",
                    "documentNotApplicable": false,
                    "documentTypeName": "29. Visiting, mail and telephone policies, as required by 102 CMR 3.07(9) and including  procedures required by 102 CMR 3.07(9)(f)1 and 2",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApafUAC",
                    "documentName": "Runaway Policy",
                    "documentNotApplicable": false,
                    "documentTypeName": "30. Runaway procedures, as required by 102 CMR 3.07(10)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006ApajUAC",
                    "documentName": "Search Policy",
                    "documentNotApplicable": false,
                    "documentTypeName": "31. Policy describing search procedures, as required by 102 CMR 3.07(11)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006AUpHUAW",
                    "documentName": "Insurance Certificate",
                    "documentNotApplicable": false,
                    "documentTypeName": "32. Plan for transportation, including ratio, as required by 102 CMR 3.07(12), including:  documentation of insurance coverage, as required by 102 CMR 3.07(12)(g)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": false,
                    "isReturnedForRevision": true,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Returned for Revision"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1Bf1000004x8N0EAI",
                    "documentName": "Building Inspection",
                    "documentNotApplicable": false,
                    "documentTypeName": "33. Current Certificate of Inspection or Use and Occupancy Permit issued by the Department  of Public Safety or the local building inspector, as required by 102 CMR 3.08(1)(a)",
                    "documentTypeNotApplicable": false,
                    "expirationDate": "2019-12-06",
                    "helpText": "",
                    "isLegacyDocumentType": false,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": false,
                    "isUnsubmitted": false,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Provider",
                    "status": "Reviewed",
                    "uploadedDate": "2018-12-06"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1Bf1000004x8N1EAI",
                    "documentName": "Health Inspection",
                    "documentNotApplicable": false,
                    "documentTypeName": "34. Report from the appropriate health inspector documenting that the facility or program is in compliance with 105 CMR 410.000 (Chapter II of the State Sanitary Code) as required by  102 CMR 3.08(1)(b)",
                    "documentTypeNotApplicable": true,
                    "expirationDate": "2019-11-29",
                    "helpText": "",
                    "isLegacyDocumentType": false,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": false,
                    "isUnsubmitted": false,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Provider",
                    "status": "Reviewed",
                    "uploadedDate": "2018-11-29"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1Bf1000004x8N2EAI",
                    "documentName": "Fire Inspection",
                    "documentNotApplicable": false,
                    "documentTypeName": "35. Documentation that the facility or program has had a Fire Inspection by the local fire  department, as required by 102 CMR 3.08(1)(c)",
                    "documentTypeNotApplicable": false,
                    "expirationDate": "2019-10-29",
                    "helpText": "",
                    "isLegacyDocumentType": false,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": false,
                    "isUnsubmitted": false,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Provider",
                    "status": "Reviewed",
                    "uploadedDate": "2018-10-29"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006AfPIUA0",
                    "documentName": "Emergency Prepareness",
                    "documentNotApplicable": false,
                    "documentTypeName": "36. Plan detailing procedures for meeting potential emergencies as required by 102 CMR  3.08(2)(a)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000006AfQBUA0",
                    "documentName": "Lead free paint inspection",
                    "documentNotApplicable": false,
                    "documentTypeName": "37. Documentation of lead-free paint inspection if applicable, on the approved form as required by  102 CMR 3.08(4)(b)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": false,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": false,
                    "isUnsubmitted": false,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Provider",
                    "status": "Reviewed"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1Bf1000004xpAhEAI",
                    "documentName": "Swimming Policy",
                    "documentNotApplicable": false,
                    "documentTypeName": "38. Plan for monitoring student safety around swimming areas, if applicable, as required by  102 CMR 3.08(5)(g)",
                    "documentTypeNotApplicable": false,
                    "expirationDate": "2020-02-15",
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": true,
                    "isOtherStatus": false,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Legacy Reviewed",
                    "uploadedDate": "2021-03-30"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000008fO95UAE",
                    "documentName": "Evidence and Compliance with REAP",
                    "documentNotApplicable": false,
                    "documentTypeName": "39. Evidence of compliance with St. 1983, c. 233, Revenue Enforcement and Protection Program  (REAP) on a form provided by the Department with the initial application (tax certification  statement as part of application)",
                    "documentTypeNotApplicable": false,
                    "helpText": "This document does not need to be submitted here; the Tax Cerification form submitted with your transaction will suffice",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Submitted"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000008fO9BUAU",
                    "documentName": "The applicant's completed CORI affidavit",
                    "documentNotApplicable": false,
                    "documentTypeName": "40. The applicant's completed CORI affidavit. If designated CORI reviewer has changed since",
                    "documentTypeNotApplicable": false,
                    "helpText": "No documents need to be submitted here; BRC forms are submitted through a transaction",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Unsubmitted"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1B3Z000008fO9CUAU",
                    "documentName": "Completed variance request form.",
                    "documentNotApplicable": false,
                    "documentTypeName": "Completed variance request form for any variance the program is seeking to renew.",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Unsubmitted"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1Bf1000004x8N6EAI",
                    "documentName": "Restraint Coordinator and Safety Committee members",
                    "documentNotApplicable": false,
                    "documentTypeName": "Please provide the name of the Restraint Coordinator for your program along with the names of all Safety committee members and their titles",
                    "documentTypeNotApplicable": false,
                    "expirationDate": "2019-10-25",
                    "helpText": "",
                    "isLegacyDocumentType": false,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": false,
                    "isUnsubmitted": false,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Provider",
                    "status": "Reviewed",
                    "uploadedDate": "2018-10-25"
                },
                {
                    "category": "Residential Policy Verification",
                    "documentId": "a1Bf1000004xpAiEAI",
                    "documentName": "Restraint Coordinator and Safety Committee members",
                    "documentNotApplicable": false,
                    "documentTypeName": "Please provide the name of the Restraint Coordinator for your program along with the names of all Safety committee members and their titles",
                    "documentTypeNotApplicable": false,
                    "expirationDate": "2019-12-17",
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Reviewed",
                    "uploadedDate": "2018-12-17"
                }
            ],
            "isAllDocsReviewed": false
        },
        {
            "categoryName": "In addition, for temporary shelter home programs: 102 CMR 3.03(1)(b)",
            "innerFields": [
                {
                    "category": "In addition, for temporary shelter home programs: 102 CMR 3.03(1)(b)",
                    "documentId": "a1B3Z000008fO94UAE",
                    "documentName": "Statement of shelter home parents qualifications",
                    "documentNotApplicable": false,
                    "documentTypeName": "1. Statement identifying qualifications of shelter home parents as required by 102 CMR 3.09(2)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Unsubmitted"
                },
                {
                    "category": "In addition, for temporary shelter home programs: 102 CMR 3.03(1)(b)",
                    "documentId": "a1Bf1000004xpAkEAI",
                    "documentName": "Physical requirements for shelter homes",
                    "documentNotApplicable": false,
                    "documentTypeName": "2. Physical requirements for shelter homes as required by 102 CMR 3.09(3)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Unsubmitted"
                },
                {
                    "category": "In addition, for temporary shelter home programs: 102 CMR 3.03(1)(b)",
                    "documentId": "a1Bf1000004xpAlEAI",
                    "documentName": "Plan for orientation of shelter home parents",
                    "documentNotApplicable": false,
                    "documentTypeName": "3. Plan for orientation of shelter home parents as required by 102 CMR 3.09(4)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Unsubmitted"
                },
                {
                    "category": "In addition, for temporary shelter home programs: 102 CMR 3.03(1)(b)",
                    "documentId": "a1Bf1000004xpAmEAI",
                    "documentName": "Procedure for completion of shelter home assessment/approval (SHELTER HOME ONLY)",
                    "documentNotApplicable": false,
                    "documentTypeName": "4. Procedures for completion of shelter home assessments and approval of shelter homes as  required by 102 CMR 3.09(5)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Unsubmitted"
                },
                {
                    "category": "In addition, for temporary shelter home programs: 102 CMR 3.03(1)(b)",
                    "documentId": "a1Bf1000004xpAnEAI",
                    "documentName": "Plan for ongoing training of shelter home parents",
                    "documentNotApplicable": false,
                    "documentTypeName": "5. Plan for ongoing training of shelter home parents as required by 102 CMR 3.09(8)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Unsubmitted"
                },
                {
                    "category": "In addition, for temporary shelter home programs: 102 CMR 3.03(1)(b)",
                    "documentId": "a1B3Z000006AfSkUAK",
                    "documentName": "General shelter home agreements",
                    "documentNotApplicable": false,
                    "documentTypeName": "6. General shelter home parent agreement and agreement upon placement of an individual  child as required by 102 CMR 3.09(9)(a) and (b)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Unsubmitted"
                },
                {
                    "category": "In addition, for temporary shelter home programs: 102 CMR 3.03(1)(b)",
                    "documentId": "a1B3Z000008fO9AUAU",
                    "documentName": "General shelter home agreements",
                    "documentNotApplicable": false,
                    "documentTypeName": "6. General shelter home parent agreement and agreement upon placement of an individual  child as required by 102 CMR 3.09(9)(a) and (b)",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": true,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": true,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Umbrella",
                    "status": "Reviewed"
                }
            ],
            "isAllDocsReviewed": false
        },
        {
            "categoryName": "Miscellaneous",
            "innerFields": [
                {
                    "category": "Miscellaneous",
                    "documentId": "a1Bf10000055BWbEAM",
                    "documentName": "Miscellaneous",
                    "documentNotApplicable": false,
                    "documentTypeName": "Miscellaneous",
                    "documentTypeNotApplicable": false,
                    "helpText": "",
                    "isLegacyDocumentType": false,
                    "isLegacyReviewed": false,
                    "isOtherStatus": true,
                    "isReturnedForRevision": false,
                    "isUmbrella": false,
                    "isUnsubmitted": true,
                    "programType": "Temporary Shelter",
                    "providerType": "Temporary Shelter",
                    "responsibleParty": "Provider",
                    "status": "Unsubmitted"
                }
            ],
            "isAllDocsReviewed": false
        }
    ];
    isUpload = false;
    showModal = false;

    openViewModal() {
        console.log('View Clicked')
        // this[NavigationMixin.Navigate]({
        //   type: 'standard__namedPage',
        //   attributes: {
        //       pageName: 'filePreview'
        //   },
        //   state : {
        //       recordIds: '06903000001rMiAAAU',
        //       selectedRecordId:'06903000001rMiAAAU'
        //   }
        // })

        window.open('https://mtxgroupinc.sharepoint.com/:w:/r/sites/DESE_Demo/_layouts/15/Doc.aspx?sourcedoc=%7B580910F2-C29C-44CE-8C94-24161362CACD%7D&file=I-0370%20Visit%20Summary%20Report.docx&action=default&mobileredirect=true', "_blank");
      }

    openUploadDocumentPage() {
        this.isUpload = true;
        this.showModal = true;
    }

    closeModal() {
        this.showModal = false;
        this.isUpload = false;
    }

    handleUploadFinished() {
        this.closeModal();
    }
}