/*
*   Class Name: Program_Helper
*   Description: Helper class of program
*  
*                                                             
*/
public with sharing class Program_Helper {
    public static final String  APP_TYPE_RTEM = 'Commercial_Real_Time_Energy_Management';
    public static final String  APP_TYPE_NYSUN_COMMERCIAL = 'NY_Sun_Commercial';
    public static final String  APP_TYPE_NYSUN_RESIDENTIAL = 'NY_Sun_Residential';
    public static final String  APP_TYPE_NYSUN_BOTH = 'Both';
    public static final String  APP_TYPE_PS = 'RHNY_Pellet_Stove';
    public static final String  APP_TYPE_CT = 'Clean_Transportation';
    public static final String  APP_TYPE_ZEV = 'Zero_Emission_Vehicles';
    public static final String  APP_TYPE_CHP = 'Onsite_Power_Combined_Heat_and_Power';
    public static final String  APP_TYPE_LARGE_GSHP = 'GSHP_Large_System';
    public static final String  APP_TYPE_SMALL_GSHP = 'GSHP_Small_System';
    public static final String  APP_TYPE_GSHP_ALL = 'GSHP_ALL_SYSTEM';
    public static final String  APP_TYPE_GSHP_ALL_VALUE = 'Ground Soure Heat Pump Program - All System Sizes';
    public static final String  STATUS_ACTIVE = 'Active';
    
    public static final String PROGRAM_FAMILY_NEW_CONSTRUCTION = 'New Construction';
}