/*
* Class Name:  ProjectPurchaseOrder_Helper
* Description: Helper class dealing with Project Purchase Orde records
* Author/Date:      
*                                                            
*/
public class ProjectPurchaseOrder_Helper {
    public static final String PROJECT_PURCHASE_ORDER_API_NAME = 'Project_Purchase_Order__c';
    public static final String PROJECT_PURCHASE_ORDER_PO_STATUS_API_NAME = 'PO_Status__c';
    public static final String PROJECT_PURCHASE_ORDER_BUDGET_STATUS_API_NAME = 'Budget_Status__c';
    public static final String PO_STATUS_APPROVED = 'Approved';
    public static final String PO_STATUS_CLOSED = 'Closed';
    public static final String PO_STATUS_DISPATCHED = 'Dispatched';
}