/*
* Name: ProjectDeliverables_Helper
* Author/Date: Harshit Jain ,  5/20/2016
* Description: Helper class for Project Deliverables
*
*/

public with sharing class ProjectDeliverables_Helper{

	public static final String STATUS_SCHEDULED = 'Scheduled';
	public static final String STATUS_APPROVED = 'Approved';

	public static final String STATUS_SUBMITTED = 'Submitted';
  public static final String STATUS_UNSUBMITTED = 'Unsubmitted';

}