public with sharing class PsrNewFosterPermitController {
    @AuraEnabled
    public static void saveQuestionnaire(String jsonString){

    }
    @AuraEnabled
    public static void getPersonalInfo(String applicationId){

    }
    @AuraEnabled
    public static void savePersonalInfo(String jsonString,String applicationId){

    }
    @AuraEnabled
    public static void saveFosterAdoptionHistory(String jsonString){

    }
}