/*
* Class Name: TransactionLogDetail_Helper
* Description: Helper class dealing with Transaction_Log__c records
* Author/Date: Ajay Gautam / July 10, 2016
*/
public with sharing class TransactionLogDetail_Helper {
  
  public static final String STATUS_SUCCESS = 'Success';
  public static final String STATUS_ERROR = 'Error';
  public static final String STATUS_INITIATED = 'Initiated';
  
  public static final String PROJECT_INVOICE_LOOKUP_API_NAME = 'Project_Invoice__c';
  public static final String PROJECT_CONTRACT_LOOKUP_API_NAME = 'Project_Contract__c';
  
}